# The http configuration part for integration with other system
retrofit:
  connection:
    readTimeout: 10000
    writeTimeout: 10000
    connectTimeout: 10000
    maxIdleConnections: 5 # The maximum number of idle connections for each address.
    keepAliveDuration: 5 # The time (minutes) to live for each idle connections.
    retryTimes: 5

  # identity: current available
  # baseUrl: the base part of business system url, would be changed by nginx location, "/" is not required to be the end of url
  # https://192.30.255.117:80
  endpoints:
#    - identity: default
#      baseUrl: http://127.0.0.1:${random.int(10000,10500)}
    - identity: github
      baseUrl: https://api.github.com
